config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    get 'customers/index'
    get 'customers/show'
    get 'customers/edit'
  end
  namespace :customer do
    get 'addresses/index'
    get 'addresses/edit'
  end
  namespace :public do
    get 'addresses/index'
    get 'addresses/edit'
  end
  namespace :customer do
    get 'users/show'
  end
# 顧客用
# URL /customers/sign_in ...
devise_for :customers,skip: [:passwords,], controllers: {
  registrations: "customer/registrations",
  sessions: 'customer/sessions'
}
# 16,17行目↑どこのコントローラーを参照しているか



# 管理者用
# URL /admin/sign_in ...
devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}

# ↓'customer'の中のコントローラーを使うよという指定の文
scope module: 'customer' do
#root path
root to: 'homes#top'
get 'about' => 'homes#about'
end

#use namespace "admin"
namespace :admin do
  #root path
  root to: 'homes#top'
  resources :items
  resources :orders, only: [:index, :show, :update]
  resources :customers, only: [:index, :show, :edit, :update]
  resources :order_details, only: [:update]
  resources :genres, only: [:index, :create, :edit, :update]
end

namespace :customer do
#customer
  get 'items/search'
  post 'items/search'
  resources :items
  resources :genres, only: [:index, :edit, :update]
  resources :addresses, only: [:index, :create, :update, :destroy, :edit]
  #customer order routes

  get 'orders/complete', to: 'orders#complete'
  post 'orders/comfirm', to: 'orders#comfirm'
  resources :orders, only: [:new, :create, :index, :show]
  #customer cart_items routes
  delete 'cart_items/destroy_all', to: 'cart_items#destroy_all'

  resources :cart_items, only: [:index, :update, :create, :destroy]



  get 'users/confirm' => 'users#confirm'

  resources :users, only: [:show, :edit, :update]

  patch 'withdraw/:id' => 'users#withdraw'
  put 'withdraw/:id' => 'users#withdraw'

end


end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :orders
         has_many :addresses, dependent: :destroy
         has_many :cart_items, dependent: :destroy

end

app/models/order.rb
class Order < ApplicationRecord

 belongs_to :customer
 has_many :order_details, dependent: :destroy
 

 validates :address, :name, presence: true
 validates :postal_code, length: {is: 7}, numericality: { only_integer: true }


 enum payment_method:{クレジットカード: 0, 銀行振込:1}
 enum status:{入金待ち: 0, 入金確認:1, 製造中:2, 発送準備中:3, 発送済み:4}
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController

  def index
    @customer = Customer.all
    @customers = Customer.page(params[:page]).per(10)
  end

  def show
    @customer = Customer.find(params[:id])

  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    if @customer.update(customer_params)
      redirect_to admin_customer_path(@customer)
    else
      reder :edit
    end
  end

  private

  def customer_params
    params.require(:customer).permit(:last_name, :first_name, :email, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number, :is_deleted )
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController

before_action :authenticate_admin!

def index
 @orders = Order.all.page(params[:page]).per(10)

end

def show
 @order = Order.find(params[:id])
 @order_details = @order.order_details
end

def update
 @order = Order.find(params[:id])
 if @order.update(order_params)
  flash[:success] = "注文ステータスを変更しました"
  redirect_to admin_order_path(@order)
 else
  render "show"
 end

end

private
def order_params
 params.require(:order).permit(:status)

end

end

app/controllers/customer/addresses_controller.rb
class Customer::AddressesController < ApplicationController

  def index
    @address = Address.new
    @addresses = Address.all


  end

  def edit
    @address = Address.find(params[:id])

  end

  def create
    @address = Address.new(address_params)
    @address.customer_id = current_customer.id
    if @address.save
      flash[:notice] = "配送先を登録しました"
      redirect_to customer_addresses_path
    else
      # binding.pry
      @address = Address.new
      @addresses = Address.all
      render 'index'
    end

  end

  def update
       @address = Address.find(params[:id])
    if @address.update(address_params)
      redirect_to customer_addresses_path
    else
      reder :edit
    end

  end

  def destroy
     Address.find_by(id: params[:id]).destroy
    redirect_to customer_addresses_path, notice: "配送先を1件削除しました"
  end

  private
  def address_params
    params.require(:address).permit(:name, :postcode, :address )
  end

end

app/controllers/customer/cart_items_controller.rb
class Customer::CartItemsController < ApplicationController

  def create
    @cart_item = CartItem.new(cart_item_params)
    @cart_item.customer_id = current_customer.id
    if @cart_item.save
      redirect_to customer_cart_items_path
    else
      @cart_item = CartItem.new(cart_item_params)
      @cart_item.customer_id = current_customer.id
      @item = Item.find(params[:cart_item][:item_id])
      @genres = Genre.all
      render 'customer/items/show'
    end
  end

  def index
    @cart_items = current_customer.cart_items
    @numbers = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
  end

  def update
    cart_item = CartItem.find(params[:id])
    cart_item.update(cart_item_params)
    redirect_to customer_cart_items_path
  end

  def destroy
    cart_item = CartItem.find(params[:id])
    cart_item.destroy
    redirect_to customer_cart_items_path
  end

  def destroy_all
    @items = current_customer.cart_items.destroy_all
    redirect_to customer_cart_items_path
  end

  private
  def cart_item_params
    params.require(:cart_item).permit(:quantity, :item_id, :customer_id)
  end
end

app/controllers/customer/confirmations_controller.rb
# frozen_string_literal: true

class Customer::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/customer/homes_controller.rb
class Customer::HomesController < ApplicationController

  def top
    @genres = Genre.all
    @items = Item.all
  end

  def about
  end

end

app/controllers/customer/items_controller.rb
class Customer::ItemsController < ApplicationController
  def index
    @items = Item.all
    @genres = Genre.all
    @items = Item.page(params[:page])
  end

  def show
    @item = Item.find(params[:id])
    @cart_item = CartItem.new
    @genres = Genre.all
  end

  def search
    @items = Item.where(genre_id: params[:search][:value])
    @genres = Genre.all
    render :index
  end
end

app/controllers/customer/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Customer::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/customer/orders_controller.rb
class Customer::OrdersController < ApplicationController

 before_action :authenticate_customer!

 def new
  @order = Order.new
  @shipping_addresses = Address.where(customer_id: current_customer.id)
 end

 def comfirm
  @cart_items = current_customer.cart_items
	 @order = Order.new(
    customer_id: current_customer.id,
    payment_method: params[:order][:payment_method]
    )

  # total_priceに請求額を代入
  # @order.total_payment = billing(@order)

  # addressにresidenceの値がはいっていれば
  if params[:order][:addresses] == "residence"
   @order.postal_code = current_customer.postal_code
   @order.address     = current_customer.address
   @order.name        = current_customer.last_name +
                        current_customer.first_name

  # addressにshipping_addressesの値がはいっていれば
  elsif params[:order][:addresses] == "shipping_addresses"
   ship = Address.find(params[:order][:shipping_address_id])
    @order.postal_code = ship.postcode
    @order.address     = ship.address
    @order.name        = ship.name

    # addressにnew_addressの値がはいっていれば
  elsif params[:order][:addresses] == "new_address"
   @order.postal_code = params[:order][:postal_code]
   @order.address     = params[:order][:address]
   @order.name        = params[:order][:name]
   @ship = "1"

      # バリデーションがあるならエラーメッセージを表示
  unless @order.valid? == true
   @shipping_addresses = Address.where(customer_id: current_customer.id)
   render :new
  end
  end
 end

 def create
  @order = current_customer.orders.new(order_params)
  @order.save
  flash[:notice] = "ご注文が確定しました。"
  redirect_to customer_orders_complete_path

  # もし情報入力でnew_addressの場合ShippingAddressに保存
  if params[:order][:ship] == "1"
   current_customer.shipping_address.create(address_params)
  end

  # カート商品の情報を注文商品に移動
  @cart_items = current_customer.cart_items
  @cart_items.each do |cart_item|
      order_detail = OrderDetail.new
      order_detail.item_id = cart_item.item_id
      order_detail.order_id = @order.id
      order_detail.amount = cart_item.quantity
      order_detail.price = cart_item.item.price
      order_detail.save
  end
  # 注文完了後、カート商品を空にする
  @cart_items.destroy_all
 end

  def complete
  end

  def index
   @orders = current_customer.orders
  end

  def show
   @order = Order.find(params[:id])
   @order_details = @order.order_details
  end

 private

 def order_params
  params.require(:order).permit(:postal_code, :address, :name, :payment_method, :total_payment, :shipping_cost)
 end

 def address_params
  params.require(:order).permit(:postal_code, :address, :name)
 end


end

app/controllers/customer/passwords_controller.rb
# frozen_string_literal: true

class Customer::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/customer/registrations_controller.rb
# frozen_string_literal: true

class Customer::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/customer/sessions_controller.rb
# frozen_string_literal: true

class Customer::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]
    before_action :reject_inactive_user, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end

  def reject_inactive_user
    @user = Customer.find_by(email: params[:customer][:email])
    if @user
      if @user.valid_password?(params[:customer][:password]) && @user.is_deleted
        redirect_to new_customer_registration_path
      end
    end
  end
end

app/controllers/customer/unlocks_controller.rb
# frozen_string_literal: true

class Customer::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/customer/users_controller.rb
class Customer::UsersController < ApplicationController
  def show
    @user = Customer.find(params[:id])

  end

  def edit
    @user = Customer.find(params[:id])
  end

  def update
    @user = current_customer
    if @user.update(customer_params)
      redirect_to customer_user_path(@user)
    else
      reder :edit
    end
  end

  def confirm
    @user = current_customer

  end

  def withdraw
    @user = Customer.find(params[:id])
    @user.update(is_deleted: true)
    reset_session
    redirect_to root_path
  end

  private

  def customer_params
    params.require(:customer).permit(:last_name, :first_name, :email, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number )
  end

end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/customer/addresses_helper.rb
module Customer::AddressesHelper
end

app/helpers/customer/cart_items_helper.rb
module Customer::CartItemsHelper
end

app/views/customer/orders/comfirm.html.erb
<% provide(:title, "注文情報確認") %>
<h2 class="head-line title_h2 text-center">注文情報確認</h2>
<div calss="row">
 <div class="col-xs-9">
 <% if current_customer.cart_items.present? %>
  <table class="table table-hover table-inverse table-bordered">
   <thead>
    <tr class="info">
     <th style="background-color: #b0c4de;">商品名</th>
     <th style="background-color: #b0c4de;">単価(税込)</th>
     <th style="background-color: #b0c4de;">数量</th>
     <th style="background-color: #b0c4de;">小計</th>
    </tr>
   </thead>
   <tbody>
    <% @total = 0 %>
   <% @cart_items.each do |cart| %>
    <tr>
     <td class="text-left">
      <%= attachment_image_tag( cart.item, :image, size: "60x50", fallback: "no_image.jpg") %>
      <%= cart.item.name %>
     </td>
     <td class="text-right">
      ¥<%= 1.1*(cart.item.price) %>
     </td>
     <td class="text-right">
      <%= cart.quantity %>
     </td>
     <td class="text-right">
      ¥<%= cart.item.price * cart.quantity * 1.1 %>
     </td>
     <td>
      <% @total = @total + cart.item.price * cart.quantity * 1.1 %>
     </td>
    </tr>
   <% end %>
   </tbody>
  </table>
 </div>
 <div class="col-xs-3 billing">
  <table class="table table-hover table-condensed table-bordered">
   <tr>
    <th class="info">送料</th>
    <td class="text-right col-xs-5">¥800<% @order.shipping_cost = 800 %></td>
   </tr>
   <tr>
    <th class="info">商品合計</th>
    <td class="text-right">¥<%= @total %></td>
   </tr>
   <tr>
    <th class="info">請求金額</th>
    <td class="text-right">¥<%= @order.total_payment = @total + @order.shipping_cost %></td>
   </tr>
  </table>
 </div>
 <div class="col-xs-9 billing">
  <table class="table table-hover table-condensed table-bordered">
   <tr>
    <th  class="info">支払方法</th>
    <td class="text-left">
     <%= @order.payment_method %>
    </td>
   </tr>
   <tr>
    <th  class="info">お届け先</th>
    <td class="text-left">
     <%= "〒 #{@order.postal_code} #{@order.address} 　#{@order.name}" %>
    </td>
   </tr>
  </table>

  <!-- 表示とformを分けて記入 -->
  <div class ="col-xs-11">
   <%= form_with model: @order, url: customer_orders_path, method: :post, local: true do |f| %>
    <%= f.hidden_field :postal_code %>
    <%= f.hidden_field :address %>
    <%= f.hidden_field :name %>
    <%= f.hidden_field :payment_method %>
    <%= f.hidden_field :total_payment %>
    <%= f.hidden_field :shipping_cost, value: @order.shipping_cost %>
    <%= link_to "注文情報入力へ戻る", new_customer_order_path, data: {"turbolinks" => false}, class: "btn btn-info col-xs-3 back" %>
   　<i class="fas fa-shipping-fast fa-2x"></i>
    <%= f.submit "購入を確定する", class: "btn btn-success center-block col-xs-5" %>
   <% end %>
  </div>
 <% else %>
 <!-- if カートアイテムがない時 -->
  <p>お客様のショッピングカートに商品はありませんので注文確定ができません。</p>
  <p><%= link_to "商品一覧", customer_items_path %>から商品をお探し下さい。</p>
 <% end %>
 </div>
</div>

app/views/customer/orders/complete.html.erb
<% provide(:title, "ありがとうございました！") %>
<div class="row col-xs-12 center-block">
 <h1 class="text-center thanx">ご購入ありがとうございました！</h1><br>
  <div class="col-xs-7">
   <%= link_to "　注文履歴はこちら　", customer_orders_path, class: "glyphicon glyphicon-folder-open btn btn-info pull-right" %>
  </div>
</div>

app/views/customer/orders/index.html.erb
<% provide(:title, "注文履歴一覧") %>
<div calss="row">
 <div class="col-xs-12">
  <h2 class="head-line title_h2 text-center">注文履歴一覧</h2>
  <% if @orders.present? %>
   <table class="table table-hover table-bordered table-condensed">
    <thead>
     <tr class="info">
      <th><i class="fas fa-calendar-day"></i>注文日</th>
      <th>配送先</th>
      <th>注文商品</th>
      <th>支払金額</th>
      <th>ステータス</th>
      <th>注文詳細</th>
     </tr>
    </thead>
    <tbody>
    <% @orders.each do |order| %>
     <tr>
      <td>
    	 <%= order.created_at.strftime('%Y/%m/%d') %>
    	</td>
    	<td class="text-left">
    	 <%= order.postal_code %><br>
    	 <%= order.address %><br>
       <%= order.name %>
    	</td>
    	<td>
       <% order.order_details.each do |order_detail| %>
    	  <%= order_detail.item.name %><br>
       <% end %>
    	</td>
    	<td class="text-right">
       <%= order.total_payment.to_s(:delimited) %>円
      </td>
      <td>
       <%= order.status %>
      </td>
      <td>
       <%= link_to "注文詳細", customer_order_path(order), class: "glyphicon glyphicon-zoom-in btn btn-success" %>
      </td>
     </tr>
    <% end %>
    </tbody>
   </table>
  <% else %>
    <p>注文履歴がありません。</p>
  <% end %>
 </div>
</div>

app/views/customer/orders/new.html.erb
<% provide(:title, "注文情報入力") %>
<div class="container">
  <div class="row">
   <div class="col-xs-12">
    <h2 class="head-line title_h2 text-center">注文情報入力</h2>
   </div>
  </div>
   <% if current_customer.cart_items.present? %>

<!--エラーメッセージ-->
   <% if @order.errors.any? %>
   <div id="error_explanation">
    <h2>
     <%= I18n.t("errors.messages.not_saved",
                 count: @order.errors.count,
                 resource: @order.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
     <% @order.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
    </ul>
   </div>
   <% end %>

   <div class="row">
    <%= form_with :model => @order, url: customer_orders_comfirm_path, method: :post, local: true  do |f| %>
     <h4 class="col">支払い方法</h4>


      <div class="col-xs-10 radio">
       <%= f.radio_button :payment_method, :"クレジットカード", checked: true %>
       <span>&nbsp;クレジットカード</span>
      </div>
      <div class="col-xs-10 radio">
       <%= f.radio_button :payment_method, :"銀行振込" %>
       <span>&nbsp;銀行振り込み</span>

      </div>
      </div>

     <h4 class="col">お届け先</h4>
      <div class="col-xs-10 radio">
       <%= f.radio_button :addresses, "residence", checked: true  %>
       <span>&nbsp;ご自身の住所</span><br>
          &emsp;&emsp;<%= "〒#{current_customer.postal_code} #{current_customer.address}" %>
          <br>
          &emsp;&emsp;<%= " #{current_customer.last_name} #{current_customer.first_name}" %>
      </div>

      <% if @shipping_addresses != [] %>
       <div class="col-xs-10 radio">
        <%= f.radio_button :addresses, "shipping_addresses" %>
        <span>&nbsp;登録済住所から選択</span><br>
        <!--order_addressはshipping_addressのモデルでpostal_code+address+name-->
         &emsp;&emsp;<%= f.collection_select(:shipping_address_id, @shipping_addresses, :id, :address) %>
       </div>
       <% end %>

       <div class="new-address">
        <%= f.radio_button :addresses, "new_address" %>
        <span>&nbsp;新しいお届け先</span><br>
        <div class="row">
        <table class="table table-borderless">
        <tr>
         <th><%= f.label :"郵便番号(ハイフンなし)"%></th>
         <td><%= f.text_field :postal_code, class: "col-sm-3 form-control-static postal_code" %></td>
         <td></td>
        </tr>
        <tr>
         <th><%= f.label :"住所" %></th>
         <td><%= f.text_field :address, class: "col-sm-8 form-control-static address" %></td>
         <td></td>
        </tr>
        <tr>
         <th><%= f.label :"宛名" %></th>
         <td><%= f.text_field :name, class: "col-sm-4 form-control-static" %></td>
         <td></td>
        </tr>

        </table>
        </div>
        </div>
        <div class="row" style="display: flex; justify-content: center;">
        <%= f.submit "確認画面へ進む", class: "btn btn-primary col-xs-5" %>
        </div>

         <%#= link_to cart_items_path, class: "glyphicon glyphicon-shopping-cart btn btn-info col-xs-3 cart-back" do %>
          <!--カート(<%#= current_customer.cart_items.count %>)へ戻る-->
         <%# end %>
       <% end %>

   <% else %>
      <!-- if カートアイテムがない時 -->
      <p>お客様のショッピングカートに商品はありませんので注文情報の入力ができません。</p>
      <p><%= link_to "商品一覧", customer_items_path, class: "btn btn-warning" %>から商品をお探し下さい。</p>
   <% end %>


</div>

app/views/customer/orders/show.html.erb
<% provide(:title, "注文履歴詳細") %>
<h2 class="head-line title_h2 text-center">注文履歴詳細</h2>
<div calss="row">
 <% if @order.present? %>
  <div class="col-xs-8">
   <strong><i class="far fa-user"></i>注文情報</strong>
    <table class="table table-bordered table-condensed">
     <tbody>
      <tr>
       <th class="info">注文日</th>
       <td class="text-left"><%= @order.created_at.strftime('%Y/%m/%d') %></td>
      </tr>
      <tr>
       <th class="info">配送先</th>
       <td class="text-left"><%= @order.postal_code %><br>
        <%= @order.address %><br>
        <%= @order.name %>
       </td>
      </tr>
      <tr>
       <th class="info">支払方法</th>
       <td class="text-left"><%= @order.payment_method %></td>
      </tr>
      <tr>
       <th class="info">ステータス</th>
       <td class="text-left"><%= @order.status %></td>
      </tr>
     </tbody>
    </table>
  </div>
  <div class="col-xs-3 col-xs-offset-1 billing">
   <strong><i class="fas fa-yen-sign"></i>請求情報</strong>
    <table class="table  table-bordered table-condensed">
     <tr>
      <th class="info">商品合計</th>
      <td class="text-right col-xs-5"><%= @order.total_payment.to_s(:delimited) %>円</td>
     </tr>
     <tr>
      <th class="info">配送料</th>
      <td class="text-right col-xs-5"><%= @order.shipping_cost.to_s(:delimited) %>円</td>
     </tr>
    </table>
  </div>
  <div class="col-xs-7 order-details">
   <strong><i class="fas fa-store"></i>注文内容</strong>
    <table class="table table-striped table-bordered table-condensed">
     <thead>
  	  <tr class="info">
  	  	<th>商品</th>
  	    <th>単価(税込)</th>
  	    <th>個数</th>
  	   	<th>小計</th>
  	   </tr>
      </thead>
      <tbody>
      <% @order_details.each do |order_detail| %>
       <tr>
  	    <td><%= order_detail.item.name %></td>
  	    <td class="text-right"><%= order_detail.item.price.to_s(:delimited) %>円</td>
  	    <td class="text-right"><%= order_detail.amount %></td>
        <td class="text-right"><%= order_detail.price.to_s(:delimited) %>円</td>
       </tr>
      <% end %>
      </tbody>
     </table>
   </div>
   <% if customer_signed_in? %>
    <%= link_to "注文履歴一覧へ戻る", customer_orders_path, class: "btn btn-info btn-lg order-index-back" %>
   <% else %>
    <%= link_to "会員詳細へ戻る", admin_customer_path, class: "btn btn-info order-index-back" %>
   <% end %>
 <% else %>
  <p>注文履歴がありません。</p>
 <% end %>
</div>