config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    get 'customers/index'
    get 'customers/show'
    get 'customers/edit'
  end
  namespace :customer do
    get 'addresses/index'
    get 'addresses/edit'
  end
  namespace :public do
    get 'addresses/index'
    get 'addresses/edit'
  end
  namespace :customer do
    get 'users/show'
  end
# 顧客用
# URL /customers/sign_in ...
devise_for :customers,skip: [:passwords,], controllers: {
  registrations: "customer/registrations",
  sessions: 'customer/sessions'
}
# 16,17行目↑どこのコントローラーを参照しているか



# 管理者用
# URL /admin/sign_in ...
devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}

# ↓'customer'の中のコントローラーを使うよという指定の文
scope module: 'customer' do
#root path
root to: 'homes#top'
get 'about' => 'homes#about'
end

#use namespace "admin"
namespace :admin do
  #root path
  root to: 'homes#top'
  resources :items
  resources :orders, only: [:index, :show, :update]
  resources :customers, only: [:index, :show, :edit, :update]
  resources :order_details, only: [:update]
  resources :genres, only: [:index, :create, :edit, :update]
end

namespace :customer do
#customer
  get 'items/search'
  post 'items/search'
  resources :items
  resources :genres, only: [:index, :edit, :update]
  resources :addresses, only: [:index, :create, :update, :destroy, :edit]
  #customer order routes

  get 'orders/complete', to: 'orders#complete'
  post 'orders/comfirm', to: 'orders#comfirm'
  resources :orders, only: [:new, :create, :index, :show]
  #customer cart_items routes
  delete 'cart_items/destroy_all', to: 'cart_items#destroy_all'

  resources :cart_items, only: [:index, :update, :create, :destroy]



  get 'users/confirm' => 'users#confirm'

  resources :users, only: [:show, :edit, :update]

  patch 'withdraw/:id' => 'users#withdraw'
  put 'withdraw/:id' => 'users#withdraw'

end


end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :orders
         has_many :addresses, dependent: :destroy
         has_many :cart_items, dependent: :destroy

end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController

  def index
    @customer = Customer.all
    @customers = Customer.page(params[:page]).per(10)
  end

  def show
    @customer = Customer.find(params[:id])

  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    if @customer.update(customer_params)
      redirect_to admin_customer_path(@customer)
    else
      reder :edit
    end
  end

  private

  def customer_params
    params.require(:customer).permit(:last_name, :first_name, :email, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number, :is_deleted )
  end
end

app/controllers/customer/addresses_controller.rb
class Customer::AddressesController < ApplicationController

  def index
    @address = Address.new
    @addresses = Address.all


  end

  def edit
    @address = Address.find(params[:id])

  end

  def create
    @address = Address.new(address_params)
    @address.customer_id = current_customer.id
    if @address.save
      flash[:notice] = "配送先を登録しました"
      redirect_to customer_addresses_path
    else
      # binding.pry
      @address = Address.new
      @addresses = Address.all
      render 'index'
    end

  end

  def update
       @address = Address.find(params[:id])
    if @address.update(address_params)
      redirect_to customer_addresses_path
    else
      reder :edit
    end

  end

  def destroy
     Address.find_by(id: params[:id]).destroy
    redirect_to customer_addresses_path, notice: "配送先を1件削除しました"
  end

  private
  def address_params
    params.require(:address).permit(:name, :postcode, :address )
  end

end

app/controllers/customer/cart_items_controller.rb
class Customer::CartItemsController < ApplicationController

  def create
    @cart_item = CartItem.new(cart_item_params)
    @cart_item.customer_id = current_customer.id
    if @cart_item.save
      redirect_to customer_cart_items_path
    else
      @cart_item = CartItem.new(cart_item_params)
      @cart_item.customer_id = current_customer.id
      @item = Item.find(params[:cart_item][:item_id])
      @genres = Genre.all
      render 'customer/items/show'
    end
  end

  def index
    @cart_items = current_customer.cart_items
    @numbers = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
  end

  def update
    cart_item = CartItem.find(params[:id])
    cart_item.update(cart_item_params)
    redirect_to customer_cart_items_path
  end

  def destroy
    cart_item = CartItem.find(params[:id])
    cart_item.destroy
    redirect_to customer_cart_items_path
  end

  def destroy_all
    @items = current_customer.cart_items.destroy_all
    redirect_to customer_cart_items_path
  end

  private
  def cart_item_params
    params.require(:cart_item).permit(:quantity, :item_id, :customer_id)
  end
end

app/controllers/customer/confirmations_controller.rb
# frozen_string_literal: true

class Customer::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/customer/homes_controller.rb
class Customer::HomesController < ApplicationController

  def top
    @genres = Genre.all
    @items = Item.all
  end

  def about
  end

end

app/controllers/customer/items_controller.rb
class Customer::ItemsController < ApplicationController
  def index
    @items = Item.all
    @genres = Genre.all
    @items = Item.page(params[:page])
  end

  def show
    @item = Item.find(params[:id])
    @cart_item = CartItem.new
    @genres = Genre.all
  end

  def search
    @items = Item.where(genre_id: params[:search][:value])
    @genres = Genre.all
    render :index
  end
end

app/controllers/customer/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Customer::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/customer/orders_controller.rb
class Customer::OrdersController < ApplicationController

 before_action :authenticate_customer!

 def new
  @order = Order.new
  @shipping_addresses = Address.where(customer_id: current_customer.id)
 end

 def comfirm
  @cart_items = current_customer.cart_items
	 @order = Order.new(
    customer_id: current_customer.id,
    payment_method: params[:order][:payment_method]
    )

  # total_priceに請求額を代入
  # @order.total_payment = billing(@order)

  # addressにresidenceの値がはいっていれば
  if params[:order][:addresses] == "residence"
   @order.postal_code = current_customer.postal_code
   @order.address     = current_customer.address
   @order.name        = current_customer.last_name +
                        current_customer.first_name

  # addressにshipping_addressesの値がはいっていれば
  elsif params[:order][:addresses] == "shipping_addresses"
   ship = Address.find(params[:order][:shipping_address_id])
    @order.postal_code = ship.postcode
    @order.address     = ship.address
    @order.name        = ship.name

    # addressにnew_addressの値がはいっていれば
  elsif params[:order][:addresses] == "new_address"
   @order.postal_code = params[:order][:postal_code]
   @order.address     = params[:order][:address]
   @order.name        = params[:order][:name]
   @ship = "1"

      # バリデーションがあるならエラーメッセージを表示
  unless @order.valid? == true
   @shipping_addresses = Address.where(customer_id: current_customer.id)
   render :new
  end
  end
 end

 def create
  @order = current_customer.orders.new(order_params)
  @order.save
  flash[:notice] = "ご注文が確定しました。"
  redirect_to customer_orders_complete_path

  # もし情報入力でnew_addressの場合ShippingAddressに保存
  if params[:order][:ship] == "1"
   current_customer.shipping_address.create(address_params)
  end

  # カート商品の情報を注文商品に移動
  @cart_items = current_customer.cart_items
  @cart_items.each do |cart_item|
      order_detail = OrderDetail.new
      order_detail.item_id = cart_item.item_id
      order_detail.order_id = @order.id
      order_detail.amount = cart_item.quantity
      order_detail.price = cart_item.item.price
      order_detail.save
  end
  # 注文完了後、カート商品を空にする
  @cart_items.destroy_all
 end

  def complete
  end

  def index
   @orders = current_customer.orders
  end

  def show
   @order = Order.find(params[:id])
   @order_details = @order.order_details
  end

 private

 def order_params
  params.require(:order).permit(:postal_code, :address, :name, :payment_method, :total_payment, :shipping_cost)
 end

 def address_params
  params.require(:order).permit(:postal_code, :address, :name)
 end


end

app/controllers/customer/passwords_controller.rb
# frozen_string_literal: true

class Customer::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/customer/registrations_controller.rb
# frozen_string_literal: true

class Customer::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/customer/sessions_controller.rb
# frozen_string_literal: true

class Customer::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]
    before_action :reject_inactive_user, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end

  def reject_inactive_user
    @user = Customer.find_by(email: params[:customer][:email])
    if @user
      if @user.valid_password?(params[:customer][:password]) && @user.is_deleted
        redirect_to new_customer_registration_path
      end
    end
  end
end

app/controllers/customer/unlocks_controller.rb
# frozen_string_literal: true

class Customer::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/customer/users_controller.rb
class Customer::UsersController < ApplicationController
  def show
    @user = Customer.find(params[:id])

  end

  def edit
    @user = Customer.find(params[:id])
  end

  def update
    @user = current_customer
    if @user.update(customer_params)
      redirect_to customer_user_path(@user)
    else
      reder :edit
    end
  end

  def confirm
    @user = current_customer

  end

  def withdraw
    @user = Customer.find(params[:id])
    @user.update(is_deleted: true)
    reset_session
    redirect_to root_path
  end

  private

  def customer_params
    params.require(:customer).permit(:last_name, :first_name, :email, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number )
  end

end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/customer/addresses_helper.rb
module Customer::AddressesHelper
end

app/helpers/customer/cart_items_helper.rb
module Customer::CartItemsHelper
end

app/helpers/customer/homes_helper.rb
module Customer::HomesHelper
end

app/helpers/customer/items_helper.rb
module Customer::ItemsHelper
end

app/helpers/customer/orders_helper.rb
module Customer::OrdersHelper
end

app/views/admin/customers/edit.html.erb
<div class='container'>
  <h2>
    <%= @customer.last_name + @customer.first_name %>
    さんの会員情報編集
    </h2>
  <div class='row'>
    <div class="col-10">
    <%= form_with model: @customer, url:admin_customer_path(@customer), local:true do |f| %>
    <table class="table table-borderless">
      <tr>
        <th>会員ID</th>
        <td><%= @customer.id %></td>
        <td></td>
      </tr>
      <tr>
        <th><%= f.label :"氏名" %></th>
        <td><%= f.text_field :last_name, class: "form-control"%></td>
        <td><%= f.text_field :first_name, autofocus: true, class: "form-control" %></td>
      </tr>
      <tr>
        <th><%= f.label :"フリガナ" %></th>
        <td><%= f.text_field :last_name_kana, autofocus: true, class: "form-control" %></td>
        <td><%= f.text_field :first_name_kana, autofocus: true, class: "form-control" %></td>
      </tr>
      <tr>
        <th><%= f.label :"メールアドレス" %></th>
        <td><%= f.text_field :email, autofocus: true, autocomplete: "email", class: "form-control" %></td>
        <td></td>
      </tr>
      <tr>
        <th><%= f.label :"郵便番号" %></th>
        <td><%= f.text_field :postal_code, class: "form-control" %></td>
        <td></td>
      </tr>
      <tr>
        <th><%= f.label :"住所" %></th>
        <td colspan="2"><%= f.text_field :address, class: "form-control" %></td>
      </tr>
      <tr>
        <th><%= f.label :"電話番号" %></th>
        <td><%= f.text_field :telephone_number, class: "form-control" %></td>
        <td></td>
      </tr>
      <tr>
        <th><%= f.label :"会員ステータス" %></th>
        <td><%= f.radio_button :is_deleted, false %>
            <%= f.label :is_deleted, '有効', value: false %>
            <%= f.radio_button :is_deleted, true %>
            <%= f.label :is_deleted, '退会', value: true%></td>
        <td></td>
      </tr>
      <tr>
        <th></th>
        <td></td>
        <td></td>
      </tr>
      <tr>
        <th></th>
        <td><%= f.submit "編集内容を保存", class: "form-control" %></td>
        <td></td>
      </tr>
    </table>
    <% end %>
    </div>
  </div>
</div>

app/views/admin/customers/index.html.erb
<div class="container">
  <h4 class="col-2 m-5">会員一覧</h4>
  <div class="row" style="display: flex; justify-content: center; ">
      <table class="col-10 table table-bordered">
      <tr>
        <th class="col-1"style="background-color: #b0c4de;">会員ID</th>
        <th class="col-2"style="background-color: #b0c4de;"><u>氏名</u></th>
        <th class="col-1"style="background-color: #b0c4de;">メールアドレス</th>
        <th class="col-2"style="background-color: #b0c4de;">ステータス</th>
      </tr>
      <% @customer.each do |customer| %>
      <tr>
          <td>
                <%= customer.id %>
          </td>
          <td>
            <u><%= link_to customer.last_name + customer.first_name, admin_customer_path(customer),class: "text-dark" %></u>
          </td>
          <td>
                <%= customer.email %>
          </td>
          <td class="text-center">
            <% if customer.is_deleted == true %>
            <strong class="text-secondary">
            退会
            </strong>
            <% else %>
            <strong class="text-success">
            有効
            </strong>
            <% end %>
          </td>
      </tr>
      <% end %>

    </table>
    </div>
    <!--<div class="row">-->
    <div class="col text-center" style="display: flex; justify-content: center; ">
      <%= paginate @customers %>
    <!--</div>-->
    </div>
</div>

app/views/admin/customers/show.html.erb
<div class="container px-5 ">
  <div class="row m-3">
    <!--<div class="col-3">-->
      <h2 class="col-6 d-flex align-items-center">
        <%= @customer.last_name + @customer.first_name %>さんの登録情報
        </h2>
    <!--</div>-->
    </div>

    <table class="col-10 table table-bordered">
      <tr>
        <th class="col-2"style="background-color: #b0c4de;">会員ID</th>
        <td>
          <%= @customer.id %>
        </td>
      </tr>
      <tr>
        <th class="col-2"style="background-color: #b0c4de;">氏名</th>
          <td>
            <%= @customer.last_name + @customer.first_name %>
          </td>
      </tr>
      <tr>
        <th class="col-2"style="background-color: #b0c4de;">カナ</th>
        <td>
          <%= @customer.last_name_kana + @customer.first_name_kana %>
        </td>
      </tr>
      <tr>
        <th class="col-2"style="background-color: #b0c4de;">郵便番号</th>
        <td>
          <%= @customer.postal_code %>
        </td>
      </tr>
      <tr>
        <th class="col-2"style="background-color: #b0c4de;">住所</th>
        <td>
          <%= @customer.address %>
        </td>
      </tr>
      <tr>
        <th class="col-2"style="background-color: #b0c4de;">電話番号</th>
        <td>
          <%= @customer.telephone_number %>
        </td>
      </tr>
      <tr>
        <th class="col-2"style="background-color: #b0c4de;">メールアドレス</th>
        <td>
          <%= @customer.email %>
        </td>
        </tr>
        <tr>
        <th class="col-2"style="background-color: #b0c4de;">会員ステータス</th>
        <td>
         <% if @customer.is_deleted == true %>
            <strong class="text-secondary">
            退会
            </strong>
            <% else %>
            <strong class="text-success">
            有効
            </strong>
            <% end %>
          <%#= @customer.is_deleted ? '退会' : '有効' %>
        </td>
      </tr>
    </table>

      <%= link_to '編集する', edit_admin_customer_path, class: "btn btn-success m-3" %>
      <%= link_to '注文履歴一覧を見る', admin_orders_path, class: "btn btn-primary m-3" %>



</div>