config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    get 'customers/index'
    get 'customers/show'
    get 'customers/edit'
  end
  namespace :customer do
    get 'addresses/index'
    get 'addresses/edit'
  end
  namespace :public do
    get 'addresses/index'
    get 'addresses/edit'
  end
  namespace :customer do
    get 'users/show'
  end
# 顧客用
# URL /customers/sign_in ...
devise_for :customers,skip: [:passwords,], controllers: {
  registrations: "customer/registrations",
  sessions: 'customer/sessions'
}
# 16,17行目↑どこのコントローラーを参照しているか



# 管理者用
# URL /admin/sign_in ...
devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}

# ↓'customer'の中のコントローラーを使うよという指定の文
scope module: 'customer' do
#root path
root to: 'homes#top'
get 'about' => 'homes#about'
end

#use namespace "admin"
namespace :admin do
  #root path
  root to: 'homes#top'
  resources :items
  resources :orders, only: [:index, :show, :update]
  resources :customers, only: [:index, :show, :edit, :update]
  resources :order_details, only: [:update]
  resources :genres, only: [:index, :create, :edit, :update]
end

namespace :customer do
#customer
  get 'items/search'
  post 'items/search'
  resources :items
  resources :genres, only: [:index, :edit, :update]
  resources :addresses, only: [:index, :create, :update, :destroy, :edit]
  #customer order routes

  get 'orders/complete', to: 'orders#complete'
  post 'orders/comfirm', to: 'orders#comfirm'
  resources :orders, only: [:new, :create, :index, :show]
  #customer cart_items routes
  delete 'cart_items/destroy_all', to: 'cart_items#destroy_all'

  resources :cart_items, only: [:index, :update, :create, :destroy]



  get 'users/confirm' => 'users#confirm'

  resources :users, only: [:show, :edit, :update]

  patch 'withdraw/:id' => 'users#withdraw'
  put 'withdraw/:id' => 'users#withdraw'

end


end

app/models/order.rb
class Order < ApplicationRecord

 belongs_to :customer
 has_many :order_details, dependent: :destroy
 

 validates :address, :name, presence: true
 validates :postal_code, length: {is: 7}, numericality: { only_integer: true }


 enum payment_method:{クレジットカード: 0, 銀行振込:1}
 enum status:{入金待ち: 0, 入金確認:1, 製造中:2, 発送準備中:3, 発送済み:4}
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController

before_action :authenticate_admin!

def index
 @orders = Order.all.page(params[:page]).per(10)

end

def show
 @order = Order.find(params[:id])
 @order_details = @order.order_details
end

def update
 @order = Order.find(params[:id])
 if @order.update(order_params)
  flash[:success] = "注文ステータスを変更しました"
  redirect_to admin_order_path(@order)
 else
  render "show"
 end

end

private
def order_params
 params.require(:order).permit(:status)

end

end

app/controllers/customer/orders_controller.rb
class Customer::OrdersController < ApplicationController

 before_action :authenticate_customer!

 def new
  @order = Order.new
  @shipping_addresses = Address.where(customer_id: current_customer.id)
 end

 def comfirm
  @cart_items = current_customer.cart_items
	 @order = Order.new(
    customer_id: current_customer.id,
    payment_method: params[:order][:payment_method]
    )

  # total_priceに請求額を代入
  # @order.total_payment = billing(@order)

  # addressにresidenceの値がはいっていれば
  if params[:order][:addresses] == "residence"
   @order.postal_code = current_customer.postal_code
   @order.address     = current_customer.address
   @order.name        = current_customer.last_name +
                        current_customer.first_name

  # addressにshipping_addressesの値がはいっていれば
  elsif params[:order][:addresses] == "shipping_addresses"
   ship = Address.find(params[:order][:shipping_address_id])
    @order.postal_code = ship.postcode
    @order.address     = ship.address
    @order.name        = ship.name

    # addressにnew_addressの値がはいっていれば
  elsif params[:order][:addresses] == "new_address"
   @order.postal_code = params[:order][:postal_code]
   @order.address     = params[:order][:address]
   @order.name        = params[:order][:name]
   @ship = "1"

      # バリデーションがあるならエラーメッセージを表示
  unless @order.valid? == true
   @shipping_addresses = Address.where(customer_id: current_customer.id)
   render :new
  end
  end
 end

 def create
  @order = current_customer.orders.new(order_params)
  @order.save
  flash[:notice] = "ご注文が確定しました。"
  redirect_to customer_orders_complete_path

  # もし情報入力でnew_addressの場合ShippingAddressに保存
  if params[:order][:ship] == "1"
   current_customer.shipping_address.create(address_params)
  end

  # カート商品の情報を注文商品に移動
  @cart_items = current_customer.cart_items
  @cart_items.each do |cart_item|
      order_detail = OrderDetail.new
      order_detail.item_id = cart_item.item_id
      order_detail.order_id = @order.id
      order_detail.amount = cart_item.quantity
      order_detail.price = cart_item.item.price
      order_detail.save
  end
  # 注文完了後、カート商品を空にする
  @cart_items.destroy_all
 end

  def complete
  end

  def index
   @orders = current_customer.orders
  end

  def show
   @order = Order.find(params[:id])
   @order_details = @order.order_details
  end

 private

 def order_params
  params.require(:order).permit(:postal_code, :address, :name, :payment_method, :total_payment, :shipping_cost)
 end

 def address_params
  params.require(:order).permit(:postal_code, :address, :name)
 end


end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/customer/orders_helper.rb
module Customer::OrdersHelper
end

app/views/admin/orders/index.html.erb
<% provide(:title, "注文履歴一覧") %>
	<h2 class="head-line title_h2 text-center">注文履歴一覧</h2>
	<div class="row" style="display: flex; justify-content: center;">
		<div class="col-xs-10 col-xs-offset-1">
			<table class="table table-hover table-bordered table-condensed">
				<thead>
		    	<tr class="info">
		      		<th class="col-xs-3"><i class="far fa-clock"></i>購入日時</th>
	      			<th><i class="far fa-user"></i>購入者</th>
		      		<th class="col-xs-1">注文個数</th>
		      		<th class="col-xs-2">注文ステータス</th>
		   		</tr>
		  		</thead>
		 		<tbody>
		    	<% @orders.each do |order| %>
		      	<tr>
		        <td>
		          <%= link_to admin_order_path(order), data: {"turbolinks" => false}, :style=>"color:#528fff;"  do %>
		          	<%= order.created_at %>
		   			<% end %>
		        </td>
		        <td class="text-left">
		          <%= order.customer.last_name + order.customer.first_name %>
		        </td>
		        <td class="text-right">
		          <%= order.order_details.count %>
		        </td>
    	      	<td>
    	        	<%= order.status %>
     	      	</td>
				</tr>
		    	<% end %>
		  </tbody>
		</table>
	</div>
  <div class="text-center"><%= paginate(@orders) %></div>
</div>

app/views/admin/orders/show.html.erb
<% provide(:title, "注文履歴詳細") %>
<h2 class="head-line title_h2 text-center">注文履歴詳細</h2>
 <div class="row">
  <div class="col-md-8" >
  	<table class="table table-borderless">
  		<tr>
  			<th>購入者</th>
  			<td><%= @order.name %></td>
  			<td></td>
  		</tr>
  		<tr>
  			<th>配送先</th>
  			<td>〒<%= @order.postal_code %><%= @order.address%> <br><%= @order.name %> </td>
  			<td></td>
  		</tr>
  		<tr>
  			<th>支払い方法</th>
  			<td><%= @order.payment_method %></td>
  			<td></td>
  		</tr>
  		<%= form_for(@order, url: admin_order_path, method: :patch) do |f| %>
  		<tr>
  			<th>注文ステータス</th>
  			<td><%= f.select :status, Order.statuses.keys, class: "order_status" %></td>
  			<td><%= f.submit '更新'  ,class: "btn btn-primary btn-block" %></td>
  		</tr>
  		<% end %>
  		<tr>
  			<th></th>
  			<td></td>
  			<td></td>
  		</tr>
  		<tr>
  			<th></th>
  			<td></td>
  			<td></td>
  		</tr>
  	</table>

   </div>

	 <div class="col-md-9">
		<table class="table table-hover table-bordered table-inverse">
	   <thead>
		  <tr class="info">
		   <th class="col-xs-4">商品名</th>
       <th>単価（税込）</th>
 	     <th>数量</th>
		   <th>小計</th>
		   <th>製作ステータス</th>
	    </tr>
		 </thead>
		 <tbody>
		 <% if flash[:notice] %>
			<div class="flash">
		   <%= flash[:notice] %>
			</div>
	   <% end %>
	   <% @order_details.each do |order_detail| %>
			<tr>
		   <td class="text-left">
		    <%= order_detail.item.name %>
			 </td>
		   <td class="text-right">
			  ¥<%= order_detail.tax.to_s(:delimited) %>
			 </td>
		   <td class="text-right">
		    <%= order_detail.amount %>
			 </td>
			 <td class="text-right">
			  ¥<%= order_detail.price.to_s(:delimited) %>
			 </td>
			  <%= form_for(order_detail, url: admin_order_detail_path(order_detail), method: :patch) do |f| %>
	       <td>
			 	  <%= f.select :status, OrderDetail.statuses.keys, class: "order_status" %>
			    <%= f.submit '更新'  ,class: "btn btn-warning" %>
         </td>
		    <% end %>
			</tr>
		 <% end %>
		 </tbody>
		</table>
	 </div>
   <div class="col-md-4  billing">
		<table class="table table-hover table-bordered table-condensed">
		 <tr>
     	<th class="info">商品合計</th>
			<td>¥<%= (@order.total_payment - @order.shipping_cost).to_s(:delimited) %></td>
		 </tr>
		 <tr>
			<th class="info">送料</th>
			<td>¥<%= @order.shipping_cost.to_s(:delimited) %></td>
		 </tr>
		 <tr>
			<th class="info">請求金額合計</th>
			<td>¥<%= @order.total_payment.to_s(:delimited) %></td>
		 </tr>
	  </table>
	  </div>
    <div class="col-xs-12">
     <%= link_to "戻る", admin_orders_path, class: "glyphicon glyphicon-home btn btn-info" %>
    </div>
	 </div>
  </div>